import { JobPosting, CandidateApplication, AuditLogItem } from './types';
import { SAMPLE_PDF_BASE64 } from './sample-pdf';

export const INITIAL_JOBS: JobPosting[] = [
  {
    id: 'job-1',
    title: 'Backend Engineer',
    department: 'Engineering',
    location: 'Jakarta (Hybrid)',
    status: 'open',
    minimum_experience_months: 24,
    mandatory_skills: ['Python', 'PostgreSQL', 'Docker'],
    preferred_skills: ['Redis', 'FastAPI', 'Kubernetes', 'gRPC'],
    created_at: '2026-08-15T09:00:00Z',
    applications_count: 4,
  },
  {
    id: 'job-2',
    title: 'Frontend Specialist (React/Next.js)',
    department: 'Engineering',
    location: 'Remote',
    status: 'open',
    minimum_experience_months: 36,
    mandatory_skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    preferred_skills: ['GraphQL', 'Zustand', 'Jest', 'Cypress'],
    created_at: '2026-08-20T10:30:00Z',
    applications_count: 2,
  },
  {
    id: 'job-3',
    title: 'DevOps & Platform Lead',
    department: 'Infrastructure',
    location: 'Jakarta (On-site)',
    status: 'open',
    minimum_experience_months: 48,
    mandatory_skills: ['Kubernetes', 'Terraform', 'CI/CD', 'AWS'],
    preferred_skills: ['Prometheus', 'Grafana', 'Go', 'Security Auditing'],
    created_at: '2026-08-25T14:15:00Z',
    applications_count: 1,
  },
];

export const INITIAL_APPLICATIONS: CandidateApplication[] = [
  {
    id: 'app-101',
    job_id: 'job-1',
    candidate_id: 'cand-1',
    document_id: 'doc-1',
    candidate_name: 'Adit TriFour',
    email: 'adit.trifour@example.com',
    phone_number: '+62 812-3456-7890',
    applied_at: '2026-09-01T10:15:00Z',
    status: 'screening',
    parse_status: 'processed',
    storage_path: 'private/cv/cand-1-adit-backend.pdf',
    pdf_url: SAMPLE_PDF_BASE64,
    original_filename: 'CV_Adit_TriFour_Backend_2026.pdf',
    file_size_bytes: 1420500,
    job_fit_score: 84.4,
    score_breakdown: {
      score_version: 'v1',
      semantic_similarity: 0.82,
      semantic_weight: 0.45,
      mandatory_skill_score: 1.0,
      mandatory_skill_weight: 0.30,
      experience_score: 1.0,
      experience_weight: 0.20,
      preferred_skill_score: 0.50,
      preferred_skill_weight: 0.05,
      final_score: 84.4,
      matched_skills: ['Python', 'PostgreSQL', 'Docker', 'FastAPI', 'Redis'],
      missing_mandatory_skills: [],
    },
    cv_extraction: {
      full_name: 'Adit TriFour',
      contact: {
        email: 'adit.trifour@example.com',
        phone_number: '+62 812-3456-7890',
        linkedin_url: 'https://linkedin.com/in/adittrifour',
        portfolio_url: 'https://github.com/adittrifour',
        location: 'Jakarta, Indonesia',
      },
      summary: 'Senior Backend Developer dengan pengalamannya membangun microservice Python, REST API, dan integrasi database PostgreSQL bertekanan tinggi.',
      total_experience_months: 36,
      skills: [
        { name: 'Python 3.11', normalized_name: 'Python', category: 'Language' },
        { name: 'PostgreSQL DB', normalized_name: 'PostgreSQL', category: 'Database' },
        { name: 'Docker Container', normalized_name: 'Docker', category: 'DevOps' },
        { name: 'FastAPI Framework', normalized_name: 'FastAPI', category: 'Backend' },
        { name: 'Redis Cache', normalized_name: 'Redis', category: 'Database' },
      ],
      work_experience: [
        {
          company: 'TechNusa Solutions',
          role: 'Backend Engineer',
          start_date: '2023-01',
          end_date: 'Present',
          is_current: true,
          duration_months: 24,
          description: 'Merancang RESTful API berkinerja tinggi berbasis FastAPI dan PostgreSQL. Mengoptimalkan query database hingga 40%.',
        },
        {
          company: 'DataKreatif Digital',
          role: 'Junior Software Engineer',
          start_date: '2022-01',
          end_date: '2022-12',
          is_current: false,
          duration_months: 12,
          description: 'Pengembangan script data pipeline menggunakan Python dan Docker containerization.',
        },
      ],
      education: [
        {
          institution: 'Universitas Indonesia',
          degree: 'Sarjana Komputer (S.Kom)',
          major: 'Teknik Informatika',
          start_year: 2018,
          end_year: 2022,
        },
      ],
      certifications: ['AWS Certified Developer Associate', 'CKAD: Certified Kubernetes Application Developer'],
      projects: ['ATS CV AI Extraction Pipeline', 'Scalable E-Commerce Backend Microservices'],
      extraction_warnings: [],
    },
  },
  {
    id: 'app-102',
    job_id: 'job-1',
    candidate_id: 'cand-2',
    document_id: 'doc-2',
    candidate_name: 'Budi Santoso',
    email: 'budi.santoso@example.com',
    phone_number: '+62 856-9876-5432',
    applied_at: '2026-09-02T11:30:00Z',
    status: 'applied',
    parse_status: 'needs_review',
    storage_path: 'private/cv/cand-2-budi-scan.pdf',
    pdf_url: SAMPLE_PDF_BASE64,
    original_filename: 'Budi_Santoso_Resume_Scan.pdf',
    file_size_bytes: 2840000,
    job_fit_score: 71.8,
    score_breakdown: {
      score_version: 'v1',
      semantic_similarity: 0.72,
      semantic_weight: 0.45,
      mandatory_skill_score: 0.67,
      mandatory_skill_weight: 0.30,
      experience_score: 1.0,
      experience_weight: 0.20,
      preferred_skill_score: 0.25,
      preferred_skill_weight: 0.05,
      final_score: 71.8,
      matched_skills: ['Python', 'PostgreSQL'],
      missing_mandatory_skills: ['Docker'],
    },
    cv_extraction: {
      full_name: 'Budi Santoso',
      contact: {
        email: 'budi.santoso@example.com',
        phone_number: '+62 856-9876-5432',
        location: 'Bandung, Indonesia',
      },
      summary: 'Backend developer berpengalaman dalam Python dan relational database. Dokumen memerlukan peninjauan HR.',
      total_experience_months: 48,
      skills: [
        { name: 'Python', normalized_name: 'Python', category: 'Language' },
        { name: 'Postgre SQL', normalized_name: 'PostgreSQL', category: 'Database' },
        { name: 'Django', normalized_name: 'Django', category: 'Backend' },
      ],
      work_experience: [
        {
          company: 'Inovasi Media Utama',
          role: 'Backend Specialist',
          start_date: '2020-06',
          end_date: 'Present',
          is_current: true,
          duration_months: 48,
          description: 'Mengembangkan sistem backend transaksi dengan Python Django dan PostgreSQL.',
        },
      ],
      education: [
        {
          institution: 'Institut Teknologi Bandung',
          degree: 'Sarjana Teknik',
          major: 'Teknik Elektro',
          start_year: 2016,
          end_year: 2020,
        },
      ],
      certifications: ['Oracle Certified Associate'],
      projects: ['Core Payment Service Refactoring'],
      extraction_warnings: [
        'Halaman PDF tidak memuat layer teks lengkap. Dokumen ditandai untuk tinjauan HR.',
        'Mandatory skill "Docker" tidak terdeteksi secara otomatis, mohon verifikasi manual.',
      ],
    },
  },
  {
    id: 'app-103',
    job_id: 'job-1',
    candidate_id: 'cand-3',
    document_id: 'doc-3',
    candidate_name: 'Citra Dewi',
    email: 'citra.dewi@example.com',
    phone_number: '+62 813-1122-3344',
    applied_at: '2026-09-02T14:00:00Z',
    status: 'interview',
    parse_status: 'processed',
    storage_path: 'private/cv/cand-3-citra-backend.pdf',
    pdf_url: SAMPLE_PDF_BASE64,
    original_filename: 'CV_Citra_Dewi_Fullstack.pdf',
    file_size_bytes: 980100,
    job_fit_score: 92.5,
    score_breakdown: {
      score_version: 'v1',
      semantic_similarity: 0.91,
      semantic_weight: 0.45,
      mandatory_skill_score: 1.0,
      mandatory_skill_weight: 0.30,
      experience_score: 1.0,
      experience_weight: 0.20,
      preferred_skill_score: 0.75,
      preferred_skill_weight: 0.05,
      final_score: 92.5,
      matched_skills: ['Python', 'PostgreSQL', 'Docker', 'FastAPI', 'Kubernetes', 'Redis'],
      missing_mandatory_skills: [],
    },
    cv_extraction: {
      full_name: 'Citra Dewi',
      contact: {
        email: 'citra.dewi@example.com',
        phone_number: '+62 813-1122-3344',
        linkedin_url: 'https://linkedin.com/in/citradewi',
        location: 'Surabaya, Indonesia',
      },
      summary: 'Backend & Cloud Infrastructure Engineer dengan keahlian mendalam pada Python, FastAPI, Docker, Kubernetes, dan optimasi PostgreSQL cluster.',
      total_experience_months: 52,
      skills: [
        { name: 'Python', normalized_name: 'Python', category: 'Language' },
        { name: 'PostgreSQL', normalized_name: 'PostgreSQL', category: 'Database' },
        { name: 'Docker', normalized_name: 'Docker', category: 'DevOps' },
        { name: 'FastAPI', normalized_name: 'FastAPI', category: 'Backend' },
        { name: 'Kubernetes', normalized_name: 'Kubernetes', category: 'DevOps' },
        { name: 'Redis', normalized_name: 'Redis', category: 'Database' },
      ],
      work_experience: [
        {
          company: 'CloudNusa Indonesia',
          role: 'Senior Backend Engineer',
          start_date: '2021-03',
          end_date: 'Present',
          is_current: true,
          duration_months: 42,
          description: 'Memimpin arsitektur backend microservice berkapasitas tinggi. Memelihara cluster Kubernetes di AWS.',
        },
      ],
      education: [
        {
          institution: 'Universitas Gadjah Mada',
          degree: 'Sarjana Komputer',
          major: 'Ilmu Komputer',
          start_year: 2017,
          end_year: 2021,
        },
      ],
      certifications: ['Certified Kubernetes Administrator (CKA)', 'AWS Solutions Architect'],
      projects: ['Distributed Payment Gateway', 'AI Document Processing Service'],
      extraction_warnings: [],
    },
  },
  {
    id: 'app-104',
    job_id: 'job-1',
    candidate_id: 'cand-4',
    document_id: 'doc-4',
    candidate_name: 'Doni Pratama',
    email: 'doni.pratama@example.com',
    phone_number: '+62 878-5566-7788',
    applied_at: '2026-09-03T08:20:00Z',
    status: 'applied',
    parse_status: 'failed',
    storage_path: 'private/cv/cand-4-corrupted.pdf',
    original_filename: 'Doni_Pratama_CV_Protected.pdf',
    file_size_bytes: 450000,
    parse_error: 'PDF terproteksi kata sandi atau file corrupt. Teks tidak dapat diekstrak.',
    job_fit_score: 0.0,
    score_breakdown: {
      score_version: 'v1',
      semantic_similarity: 0.0,
      semantic_weight: 0.45,
      mandatory_skill_score: 0.0,
      mandatory_skill_weight: 0.30,
      experience_score: 0.0,
      experience_weight: 0.20,
      preferred_skill_score: 0.0,
      preferred_skill_weight: 0.05,
      final_score: 0.0,
      matched_skills: [],
      missing_mandatory_skills: ['Python', 'PostgreSQL', 'Docker'],
    },
    cv_extraction: {
      full_name: 'Doni Pratama',
      contact: {
        email: 'doni.pratama@example.com',
      },
      summary: undefined,
      total_experience_months: 0,
      skills: [],
      work_experience: [],
      education: [],
      certifications: [],
      projects: [],
      extraction_warnings: ['Ekstraksi gagal total: Berkas PDF dilindungi sandi.'],
    },
  },
  {
    id: 'app-201',
    job_id: 'job-2',
    candidate_id: 'cand-5',
    document_id: 'doc-5',
    candidate_name: 'Eka Rahmawati',
    email: 'eka.rahmawati@example.com',
    phone_number: '+62 821-4433-2211',
    applied_at: '2026-09-01T15:30:00Z',
    status: 'screening',
    parse_status: 'processed',
    storage_path: 'private/cv/cand-5-eka-frontend.pdf',
    original_filename: 'Eka_Rahmawati_Frontend_CV.pdf',
    file_size_bytes: 1150000,
    job_fit_score: 89.2,
    score_breakdown: {
      score_version: 'v1',
      semantic_similarity: 0.88,
      semantic_weight: 0.45,
      mandatory_skill_score: 1.0,
      mandatory_skill_weight: 0.30,
      experience_score: 1.0,
      experience_weight: 0.20,
      preferred_skill_score: 0.50,
      preferred_skill_weight: 0.05,
      final_score: 89.2,
      matched_skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Zustand', 'Jest'],
      missing_mandatory_skills: [],
    },
    cv_extraction: {
      full_name: 'Eka Rahmawati',
      contact: {
        email: 'eka.rahmawati@example.com',
        phone_number: '+62 821-4433-2211',
        linkedin_url: 'https://linkedin.com/in/ekarahmawati',
        portfolio_url: 'https://eka-frontend.dev',
        location: 'Yogyakarta, Indonesia',
      },
      summary: 'Frontend Engineer berpengalaman membangun aplikasi React dan Next.js dengan arsitektur UI modern, Tailwind CSS, dan komprehensif unit test.',
      total_experience_months: 40,
      skills: [
        { name: 'React.js', normalized_name: 'React', category: 'Frontend' },
        { name: 'TypeScript', normalized_name: 'TypeScript', category: 'Language' },
        { name: 'Next.js 14', normalized_name: 'Next.js', category: 'Framework' },
        { name: 'TailwindCSS', normalized_name: 'Tailwind CSS', category: 'Styling' },
        { name: 'Zustand State', normalized_name: 'Zustand', category: 'State Management' },
        { name: 'Jest Unit Test', normalized_name: 'Jest', category: 'Testing' },
      ],
      work_experience: [
        {
          company: 'Studio Digital Nusa',
          role: 'Lead Frontend Developer',
          start_date: '2023-01',
          end_date: 'Present',
          is_current: true,
          duration_months: 24,
          description: 'Mengembangkan dashboard SaaS dengan Next.js App Router dan Tailwind CSS.',
        },
      ],
      education: [
        {
          institution: 'Universitas Amikom',
          degree: 'Sarjana Komputer',
          major: 'Teknik Informatika',
          start_year: 2018,
          end_year: 2022,
        },
      ],
      certifications: ['Meta Front-End Developer Professional Certificate'],
      projects: ['Design System UI Component Library', 'Analytics Dashboard UI'],
      extraction_warnings: [],
    },
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-01T10:15:00Z',
    actor: 'HR Admin (Siti)',
    action: 'cv_uploaded',
    target_entity: 'candidate_documents',
    entity_id: 'doc-1',
    details: 'Berhasil mengunggah CV_Adit_TriFour_Backend_2026.pdf (1.4 MB) untuk lowongan Backend Engineer.',
  },
  {
    id: 'log-2',
    timestamp: '2026-09-01T10:15:15Z',
    actor: 'System AI Worker',
    action: 'cv_processing_completed',
    target_entity: 'applications',
    entity_id: 'app-101',
    details: 'Ekstraksi PyMuPDF + LLM sukses. Job-Fit Score dihitung: 84.4/100.',
  },
  {
    id: 'log-3',
    timestamp: '2026-09-02T11:30:20Z',
    actor: 'System AI Worker',
    action: 'cv_processing_completed',
    target_entity: 'applications',
    entity_id: 'app-102',
    details: 'Penolakan PDF tanpa layer teks (Zero-Text Rule). Status diset ke "needs_review".',
  },
];
